version: "3.9"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped
    networks:
      - inception

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    volumes:
      - redis:/var/lib/redis
    restart: unless-stopped
    networks:
      - inception

  static_website:
    build: ./requirements/bonus/static_website
    container_name: static_website
    env_file: .env
    ports:
      - "9999:9999"
    restart: unless-stopped
    networks:
      - inception

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - inception

  monitor:
    build: ./requirements/bonus/monitor
    container_name: monitor
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - inception

  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    env_file: .env
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - wordpress:/home/${FTP_USER}/ftp

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/oubet/data/mariadb"

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/oubet/data/wordpress"

  redis:
    name: redis
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/oubet/data/redis"

networks:
  inception:
  

